### ISSUE TITLE
Group uri/resource_uri confusion?

### ISSUE THREAD

**Issue by sbenthall** [glasgow-ipl/ietfdata#53]
```
dt = DataTracker(cache_dir=Path("cache"))
group = dt.group_from_acronym('mmusic')
drafts = dt.documents(group = group,
                      doctype = dt.document_type('draft'))
```

This errors with:

```
Traceback (most recent call last):
  File "affiliations.py", line 36, in <module>
    doctype = dt.document_type('draft')) ###
  File "/home/sb/projects/bigbang-multi/ietfdata/ietfdata/datatracker.py", line 1648, in document_type
    return self._retrieve(doc_type_uri, DocumentType)
  File "/home/sb/projects/bigbang-multi/ietfdata/ietfdata/datatracker.py", line 1367, in _retrieve
    if self._obj_is_cached(resource_uri):
  File "/home/sb/projects/bigbang-multi/ietfdata/ietfdata/datatracker.py", line 1338, in _obj_is_cached
    return self._cache_filepath(resource_uri).exists()
  File "/home/sb/projects/bigbang-multi/ietfdata/ietfdata/datatracker.py", line 1332, in _cache_filepath
    return Path(self.cache_dir, resource_uri.uri[1:-1] + ".json")
AttributeError: 'str' object has no attribute 'uri'
```

**Comment by lumisota** [comment]
``document_type()`` takes a ``DocumentTypeURI`` - the following should work:

```
dt = DataTracker(cache_dir=Path("cache"))
group = dt.group_from_acronym('mmusic')
drafts = dt.documents(group = group,
                      doctype = dt.document_type(DocumentTypeURI("/api/v1/name/doctypename/draft")))
```

**Comment by csperkins** [comment]
I'm wondering if `document_type()` and similar methods should be updated to take either a URI or a slug?
```
dt.document_type(uri=…)
```
or 
```
dt.document_type(slug="draft")
```
This would make the implementation of the library a little messy, but might simplify code that uses it somewhat.

**Comment by sbenthall** [comment]
Ah, thank you, that works @lumisota 

@csperkins what about `dt.doctype_from_slug`

**Comment by csperkins** [comment]
@sbenthall that's the other option, yeah. If we're going to be consistent with the naming, it would be `document_type_from_slug()`.
