### ISSUE TITLE
HeaderDataMailHelper crashes with bad dates

### ISSUE THREAD

**Issue by csperkins** [glasgow-ipl/ietfdata#84]
The `scan_message()` method of `HeaderDataMailHelper` can crash if given a bad date:
```
INFO:ietfdata:scan message dnsext/015459 for metadata
Traceback (most recent call last):
  File "examples/emails_2019.py", line 48, in <module>
    ml = archive.mailing_list("dnsext")
  File "/Users/csp/Projects/glasgow-ipl/ietfdata/ietfdata/mailarchive.py", line 374, in mailing_list
    self._mailing_lists[mailing_list_name] = MailingList(self._cache_dir, mailing_list_name, self._helpers)
  File "/Users/csp/Projects/glasgow-ipl/ietfdata/ietfdata/mailarchive.py", line 189, in __init__
    self._msg_metadata[msg_id] = {**(helper.scan_message(message_text)), **(self._msg_metadata[msg_id])}
  File "/Users/csp/Projects/glasgow-ipl/ietfdata/ietfdata/mailhelper_headerdata.py", line 43, in scan_message
    timestamp = datetime.fromtimestamp(time.mktime(msg_date))
OverflowError: mktime argument out of range
```

The message in question here has `Date: Wed, 14 Jun 100 05:41:34 -0700 (PDT)` (i.e., a Y2K bug in the date string). 

It may be worth checking how many message dates fail to parse across the entire archive, to see if it's worth writing a work-around.

**Comment by lumisota** [comment]
In #86, I've wrapped ```HeaderDataMailHelper```'s date parsing in a try-except block. This sets the ```timestamp``` metadata field to ```None``` if parsing fails.

I'll check how often parsing fails, and why, across the archive, and update to handle any worthwhile edge cases.

**Comment by csperkins** [comment]
Thanks! I'll leave this open for now, until we know how common these failures are.
